logging:
  level:
    root: WARN
    com.wotiwan.spring.database.repository.pool.ConnectionPool: INFO
  file:
    name: logs
    path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/medonline
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
    open-in-view: false

jwt:
  secret: 8cf7d3e8e6c45d8df94fbba76a1f4302b79d1483d5cf6f11b8f2e92d7e6e56cd
  expiration: 86400